services:
  - type: web
    name: husam-personal-site
    env: node
    plan: starter
    branch: main
    buildCommand: npm ci && npm run build
    startCommand: npm run start
    healthCheckPath: /
    envVars:
      - key: NEXT_PUBLIC_SUPABASE_URL
        sync: false
      - key: NEXT_PUBLIC_SUPABASE_ANON_KEY
        sync: false
      - key: NEXT_PUBLIC_APP_URL
        sync: false
      - key: NODE_VERSION
        value: 20.12.2
